#!/bin/bash

set -ex

if [ "$PREBUILT" = "YES" ]; then
	echo "Skipping built, PREBUILT enviroment variable is set"
else
	sbt -batch "project distilledtests-server" assembly > /dev/null
fi

export JAVA_OPTS="-Xmx13G -Xss1G"
java $JAVA_OPTS -cp server/target/scala-2.11/distilledtests-server-assembly-latest.jar distilling.server.Cmd "$@"

#export SBT_OPTS="-Xmx13G -Xss1G"
#sbt -batch "project distilledtests-server" "runMain distilling.server.Cmd $*"
