#!/bin/bash
export NODE_OPTIONS="--max_old_space_size=8192 --require /home/torp/development/type-regression/api-inference/test-runner/res/../../../api-inference/API-tracer/build/API-tracer/src/index.js"
        "$@"